# Generated by Django 2.1.7 on 2019-10-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0002_auto_20190921_2313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('semester', 'course', 'instructor')},
        ),
    ]
